sudo: false
language: node_js
node_js: stable
notifications:
  email: false
  slack:
    secure: xwUcvMqvSPLmGUYGM98jxkajL2jWG/wA1dBaN1gvSpDEJhMtxPqNSRePCBVMIiZwuqry9mZGULOV3egcsTxOC6CvNzanKnaK1+vt7yE9jbmWdBwm2uypbVNmLk8usOUHM+LFgGEJaNOCbLbg9C3yTEaFIz/pOfSQv/fBzM6zTLuFWmuePoBuTYEcG6V6J7ObL3Yz6NxgNHxH4vV/oCilRQoUR4QUtDWrsxjG1t3pwCdVuSbjIs4I1yFiOcG6XaQ4xcv1JNnP2rbI+BVUGHremDhza/w3Fpp6Li+/4CbTw8Yw3S+Ykuxme+I3njX+Qb2dd6oSeibewiF7Xm1uLAlYLGIrobcRQ/8IgphKvOY5VhfHOgAfnxHk+oY9SPTM6StAJ/omWOA09CEIRzb2DlcNAr/zHwWilVfr1KDSsD1R0jqiiA9Kbh/8FVgZHIka6ldEwdYE4c7EbWp1beGAeQ3a6NOPe6vb8xsZpeYmLmDY3VSrAIL3E8RtfM4rE/3D8DbnOkLAgbcauOrZgyVwPtDUlFoVVMjXiYtonJmyuRUS+KBL/x1wJJoK8DKoyYEc90BbYlMGkV1L6FdOY7Q80xcyK+qBKfuX4ppDiYdNHZiqJvJFVAzB+X3YFBdMgrJ8RNkAfbX52fLSFkzpKvDn1Q3v8K/xWqQ9He9+N0CEYlv1f4s=
