sudo: false
language: node_js
node_js: stable
notifications:
  email: false
  slack:
    secure: xwUcvMqvSPLmGUYGM98jxkajL2jWG/wA1dBaN1gvSpDEJhMtxPqNSRePCBVMIiZwuqry9mZGULOV3egcsTxOC6CvNzanKnaK1+vt7yE9jbmWdBwm2uypbVNmLk8usOUHM+LFgGEJaNOCbLbg9C3yTEaFIz/pOfSQv/fBzM6zTLuFWmuePoBuTYEcG6V6J7ObL3Yz6NxgNHxH4vV/oCilRQoUR4QUtDWrsxjG1t3pwCdVuSbjIs4I1yFiOcG6XaQ4xcv1JNnP2rbI+BVUGHremDhza/w3Fpp6Li+/4CbTw8Yw3S+Ykuxme+I3njX+Qb2dd6oSeibewiF7Xm1uLAlYLGIrobcRQ/8IgphKvOY5VhfHOgAfnxHk+oY9SPTM6StAJ/omWOA09CEIRzb2DlcNAr/zHwWilVfr1KDSsD1R0jqiiA9Kbh/8FVgZHIka6ldEwdYE4c7EbWp1beGAeQ3a6NOPe6vb8xsZpeYmLmDY3VSrAIL3E8RtfM4rE/3D8DbnOkLAgbcauOrZgyVwPtDUlFoVVMjXiYtonJmyuRUS+KBL/x1wJJoK8DKoyYEc90BbYlMGkV1L6FdOY7Q80xcyK+qBKfuX4ppDiYdNHZiqJvJFVAzB+X3YFBdMgrJ8RNkAfbX52fLSFkzpKvDn1Q3v8K/xWqQ9He9+N0CEYlv1f4s=
deploy:
  provider: heroku
  api_key:
    secure: uDl6LmRUa3F3bdntYTllss32D5+T8kDAt3xPON6wbYUeSgic2Ywxun/rH7fqQ1eff2y0cBKGaUeruYPwHOVp6uCwfTcVlaIjyzLEp7b5r+ScjqClAj/1DretXrHYdKZ9tSgg/94535SvzKcP9CydgcYws/mNuoWWwGNhqCz0965QVY3EovwEp/zT9hHbIWqOsP9zFb08k8HCbSvNa6SU1qpD5HN1TYL/PYJHdyITDZUQKWyDOhfyhWNnZ/sPBUlqvkdPZmo+iFq5LiN+RSAESt+SHwrKt96WY/eWgQ2rdngLRXIvofxyU07P/UMCykm2vbCWw9FQZ6PHpTGHKCLH9XO5qjF8jUFSywmv5XdwIew+SjecF2zVAkgb2+sEmv2uujcfALA2faIL8uHm7XBTXC7wZobasUFnozhZOgyUBqgiF6uyUvJUjQFNZmqsSHCR9ETh2Tp8h/u2VJepz2g4wNNDJcOEh5JQUfT0REZkrzQXFshRTfJPQLZpqp7KcC7M6h1/l2l2/kEzxP+R8J0vAom27Pzd9O2L53jayA3mbTWJ9niw+IInxejHQChqBDdH1iIBzskIWTUWjk6OJaAJY9giarS4r81Dhi+a/k+BvTyhqy+v2As1vJsM07JasP6a8TmLRcjSEk6Qwm1ITpE5+4Ad/8IonyAwMgVsgL261GU=
  app: fathomless-river-84575
  on:
    repo: 9renpoto/hubot
